// <auto-generated />
using System;
using Convidados_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConvidadosMVC.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497");

            modelBuilder.Entity("Convidados_MVC.Models.Convidado", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Confirmacao");

                    b.Property<DateTime>("DataInclusao");

                    b.Property<string>("IdUsuario");

                    b.Property<string>("Nome");

                    b.Property<string>("Padrinho");

                    b.Property<string>("TipoConvidado");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Convidado");
                });

            modelBuilder.Entity("Convidados_MVC.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataInclusao");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Convidados_MVC.Models.Convidado", b =>
                {
                    b.HasOne("Convidados_MVC.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
